/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baice_bc_im_silk_SilkEncoder */

#ifndef _Included_com_baice_bc_im_silk_SilkEncoder
#define _Included_com_baice_bc_im_silk_SilkEncoder
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL Java_com_baice_bc_1im_1silk_SilkEncoder_init
  (JNIEnv *, jclass);



JNIEXPORT jint JNICALL Java_com_baice_bc_1im_1silk_SilkEncoder_encode
  (JNIEnv *, jclass, jshortArray, jbyteArray, jint);



JNIEXPORT void JNICALL Java_com_baice_bc_1im_1silk_SilkEncoder_reset(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_baice_bc_1im_1silk_SilkEncoder_exit(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
