/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baice_bc_im_silk_SilkDecoder */

#ifndef _Included_com_baice_bc_im_silk_SilkDecoder
#define _Included_com_baice_bc_im_silk_SilkDecoder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_baice_bc_1im_1silk_SilkDecoder_decode
  (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_baice_bc_1im_1silk_SilkDecoder_reset(JNIEnv *, jclass);

JNIEXPORT jdouble JNICALL Java_com_baice_bc_1im_1silk_SilkDecoder_getRecordLength
        (JNIEnv *, jclass, jstring);

void decode_callback(short outBuf[], uint32_t outLen);

#ifdef __cplusplus
}
#endif
#endif
